{ _readableState:
		 { highWaterMark: 16384,
				 buffer: [],
				 length: 0,
				 pipes: null,
				 pipesCount: 0,
				 flowing: false,
				 ended: false,
				 endEmitted: false,
				 reading: false,
				 calledRead: false,
				 sync: true,
				 needReadable: false,
				 emittedReadable: false,
				 readableListening: false,
				 objectMode: false,
				 ranOut: false,
				 awaitDrain: 0,
				 readingMore: false,
				 decoder: null },
		readable: true,
		domain: null,
		_events: {},
		_maxListeners: 10,
		socket:
		 { _connecting: false,
				 _handle:
						{ fd: 11,
								writeQueueSize: 0,
								owner: [Circular],
								onread: [Function: onread],
								reading: true },
				 _readableState:
						{ highWaterMark: 16384,
								buffer: [],
								length: 0,
								pipes: null,
								pipesCount: 0,
								flowing: false,
								ended: false,
								endEmitted: false,
								reading: true,
								calledRead: true,
								sync: false,
								needReadable: true,
								emittedReadable: false,
								readableListening: false,
								objectMode: false,
								ranOut: false,
								awaitDrain: 0,
								readingMore: false,
								decoder: null },
				 readable: true,
				 domain: null,
				 _events:
						{ end: [Object],
								finish: [Function: onSocketFinish],
								_socketEnd: [Function: onSocketEnd],
								free: [Function],
								close: [Object],
								agentRemove: [Function],
								drain: [Function: ondrain],
								error: [Function: socketErrorListener],
								connect: undefined },
				 _maxListeners: 10,
				 _writableState:
						{ highWaterMark: 16384,
								objectMode: false,
								needDrain: false,
								ending: false,
								ended: false,
								finished: false,
								decodeStrings: false,
								length: 0,
								writing: false,
								sync: false,
								bufferProcessing: false,
								onwrite: [Function],
								writecb: null,
								writelen: 0,
								buffer: [] },
				 writable: true,
				 allowHalfOpen: false,
				 onend: [Function: socketOnEnd],
				 destroyed: false,
				 errorEmitted: false,
				 bytesRead: 1460,
				 _bytesDispatched: 84,
				 _pendingData: null,
				 _pendingEncoding: '',
				 parser:
						{ _headers: [],
								_url: '',
								onHeaders: [Function: parserOnHeaders],
								onHeadersComplete: [Function: parserOnHeadersComplete],
								onBody: [Function: parserOnBody],
								onMessageComplete: [Function: parserOnMessageComplete],
								socket: [Circular],
								incoming: [Circular],
								maxHeaderPairs: 2000,
								onIncoming: [Function: parserOnIncomingClient] },
				 _httpMessage:
						{ domain: null,
								_events: [Object],
								_maxListeners: 10,
								output: [],
								outputEncodings: [],
								writable: true,
								_last: true,
								chunkedEncoding: false,
								shouldKeepAlive: true,
								useChunkedEncodingByDefault: false,
								sendDate: false,
								_hasBody: true,
								_trailer: '',
								finished: true,
								_hangupClose: false,
								socket: [Circular],
								connection: [Circular],
								agent: [Object],
								socketPath: undefined,
								method: 'GET',
								path: '/jquery-1.9.1.min.js',
								_headers: [Object],
								_headerNames: [Object],
								_header: 'GET /jquery-1.9.1.min.js HTTP/1.1\r\nHost: code.jquery.com\r\nConnection: keep-alive\r\n\r\n',
								_headerSent: true,
								parser: [Object],
								res: [Circular] },
				 ondata: [Function: socketOnData] },
		connection:
		 { _connecting: false,
				 _handle:
						{ fd: 11,
								writeQueueSize: 0,
								owner: [Circular],
								onread: [Function: onread],
								reading: true },
				 _readableState:
						{ highWaterMark: 16384,
								buffer: [],
								length: 0,
								pipes: null,
								pipesCount: 0,
								flowing: false,
								ended: false,
								endEmitted: false,
								reading: true,
								calledRead: true,
								sync: false,
								needReadable: true,
								emittedReadable: false,
								readableListening: false,
								objectMode: false,
								ranOut: false,
								awaitDrain: 0,
								readingMore: false,
								decoder: null },
				 readable: true,
				 domain: null,
				 _events:
						{ end: [Object],
								finish: [Function: onSocketFinish],
								_socketEnd: [Function: onSocketEnd],
								free: [Function],
								close: [Object],
								agentRemove: [Function],
								drain: [Function: ondrain],
								error: [Function: socketErrorListener],
								connect: undefined },
				 _maxListeners: 10,
				 _writableState:
						{ highWaterMark: 16384,
								objectMode: false,
								needDrain: false,
								ending: false,
								ended: false,
								finished: false,
								decodeStrings: false,
								length: 0,
								writing: false,
								sync: false,
								bufferProcessing: false,
								onwrite: [Function],
								writecb: null,
								writelen: 0,
								buffer: [] },
				 writable: true,
				 allowHalfOpen: false,
				 onend: [Function: socketOnEnd],
				 destroyed: false,
				 errorEmitted: false,
				 bytesRead: 1460,
				 _bytesDispatched: 84,
				 _pendingData: null,
				 _pendingEncoding: '',
				 parser:
						{ _headers: [],
								_url: '',
								onHeaders: [Function: parserOnHeaders],
								onHeadersComplete: [Function: parserOnHeadersComplete],
								onBody: [Function: parserOnBody],
								onMessageComplete: [Function: parserOnMessageComplete],
								socket: [Circular],
								incoming: [Circular],
								maxHeaderPairs: 2000,
								onIncoming: [Function: parserOnIncomingClient] },
				 _httpMessage:
						{ domain: null,
								_events: [Object],
								_maxListeners: 10,
								output: [],
								outputEncodings: [],
								writable: true,
								_last: true,
								chunkedEncoding: false,
								shouldKeepAlive: true,
								useChunkedEncodingByDefault: false,
								sendDate: false,
								_hasBody: true,
								_trailer: '',
								finished: true,
								_hangupClose: false,
								socket: [Circular],
								connection: [Circular],
								agent: [Object],
								socketPath: undefined,
								method: 'GET',
								path: '/jquery-1.9.1.min.js',
								_headers: [Object],
								_headerNames: [Object],
								_header: 'GET /jquery-1.9.1.min.js HTTP/1.1\r\nHost: code.jquery.com\r\nConnection: keep-alive\r\n\r\n',
								_headerSent: true,
								parser: [Object],
								res: [Circular] },
				 ondata: [Function: socketOnData] },
		httpVersion: '1.1',
		complete: false,
		headers:
		 { 'accept-ranges': 'bytes',
				 'access-control-allow-origin': '*',
				 'cache-control': 'max-age=2592000',
				 'content-type': 'application/x-javascript; charset=utf-8',
				 date: 'Tue, 02 Apr 2013 21:30:28 GMT',
				 expires: 'Thu, 02 May 2013 21:30:28 GMT',
				 'last-modified': 'Tue, 05 Feb 2013 00:56:40 GMT',
				 server: 'ECS (fcn/41B6)',
				 vary: 'Accept-Encoding',
				 'x-cache': 'HIT',
				 'content-length': '92629' },
		trailers: {},
		_pendings: [],
		_pendingIndex: 0,
		url: '',
		method: null,
		statusCode: 200,
		client:
		 { _connecting: false,
				 _handle:
						{ fd: 11,
								writeQueueSize: 0,
								owner: [Circular],
								onread: [Function: onread],
								reading: true },
				 _readableState:
						{ highWaterMark: 16384,
								buffer: [],
								length: 0,
								pipes: null,
								pipesCount: 0,
								flowing: false,
								ended: false,
								endEmitted: false,
								reading: true,
								calledRead: true,
								sync: false,
								needReadable: true,
								emittedReadable: false,
								readableListening: false,
								objectMode: false,
								ranOut: false,
								awaitDrain: 0,
								readingMore: false,
								decoder: null },
				 readable: true,
				 domain: null,
				 _events:
						{ end: [Object],
								finish: [Function: onSocketFinish],
								_socketEnd: [Function: onSocketEnd],
								free: [Function],
								close: [Object],
								agentRemove: [Function],
								drain: [Function: ondrain],
								error: [Function: socketErrorListener],
								connect: undefined },
				 _maxListeners: 10,
				 _writableState:
						{ highWaterMark: 16384,
								objectMode: false,
								needDrain: false,
								ending: false,
								ended: false,
								finished: false,
								decodeStrings: false,
								length: 0,
								writing: false,
								sync: false,
								bufferProcessing: false,
								onwrite: [Function],
								writecb: null,
								writelen: 0,
								buffer: [] },
				 writable: true,
				 allowHalfOpen: false,
				 onend: [Function: socketOnEnd],
				 destroyed: false,
				 errorEmitted: false,
				 bytesRead: 1460,
				 _bytesDispatched: 84,
				 _pendingData: null,
				 _pendingEncoding: '',
				 parser:
						{ _headers: [],
								_url: '',
								onHeaders: [Function: parserOnHeaders],
								onHeadersComplete: [Function: parserOnHeadersComplete],
								onBody: [Function: parserOnBody],
								onMessageComplete: [Function: parserOnMessageComplete],
								socket: [Circular],
								incoming: [Circular],
								maxHeaderPairs: 2000,
								onIncoming: [Function: parserOnIncomingClient] },
				 _httpMessage:
						{ domain: null,
								_events: [Object],
								_maxListeners: 10,
								output: [],
								outputEncodings: [],
								writable: true,
								_last: true,
								chunkedEncoding: false,
								shouldKeepAlive: true,
								useChunkedEncodingByDefault: false,
								sendDate: false,
								_hasBody: true,
								_trailer: '',
								finished: true,
								_hangupClose: false,
								socket: [Circular],
								connection: [Circular],
								agent: [Object],
								socketPath: undefined,
								method: 'GET',
								path: '/jquery-1.9.1.min.js',
								_headers: [Object],
								_headerNames: [Object],
								_header: 'GET /jquery-1.9.1.min.js HTTP/1.1\r\nHost: code.jquery.com\r\nConnection: keep-alive\r\n\r\n',
								_headerSent: true,
								parser: [Object],
								res: [Circular] },
				 ondata: [Function: socketOnData] },
		_consuming: false,
		_dumped: false,
		httpVersionMajor: 1,
		httpVersionMinor: 1,
		upgrade: false,
		req:
		 { domain: null,
				 _events: { response: undefined, socket: undefined },
				 _maxListeners: 10,
				 output: [],
				 outputEncodings: [],
				 writable: true,
				 _last: true,
				 chunkedEncoding: false,
				 shouldKeepAlive: true,
				 useChunkedEncodingByDefault: false,
				 sendDate: false,
				 _hasBody: true,
				 _trailer: '',
				 finished: true,
				 _hangupClose: false,
				 socket:
						{ _connecting: false,
								_handle: [Object],
								_readableState: [Object],
								readable: true,
								domain: null,
								_events: [Object],
								_maxListeners: 10,
								_writableState: [Object],
								writable: true,
								allowHalfOpen: false,
								onend: [Function: socketOnEnd],
								destroyed: false,
								errorEmitted: false,
								bytesRead: 1460,
								_bytesDispatched: 84,
								_pendingData: null,
								_pendingEncoding: '',
								parser: [Object],
								_httpMessage: [Circular],
								ondata: [Function: socketOnData] },
				 connection:
						{ _connecting: false,
								_handle: [Object],
								_readableState: [Object],
								readable: true,
								domain: null,
								_events: [Object],
								_maxListeners: 10,
								_writableState: [Object],
								writable: true,
								allowHalfOpen: false,
								onend: [Function: socketOnEnd],
								destroyed: false,
								errorEmitted: false,
								bytesRead: 1460,
								_bytesDispatched: 84,
								_pendingData: null,
								_pendingEncoding: '',
								parser: [Object],
								_httpMessage: [Circular],
								ondata: [Function: socketOnData] },
				 agent:
						{ domain: null,
								_events: [Object],
								_maxListeners: 10,
								options: {},
								requests: {},
								sockets: [Object],
								maxSockets: 5,
								createConnection: [Function] },
				 socketPath: undefined,
				 method: 'GET',
				 path: '/jquery-1.9.1.min.js',
				 _headers: { host: 'code.jquery.com' },
				 _headerNames: { host: 'Host' },
				 _header: 'GET /jquery-1.9.1.min.js HTTP/1.1\r\nHost: code.jquery.com\r\nConnection: keep-alive\r\n\r\n',
				 _headerSent: true,
				 parser:
						{ _headers: [],
								_url: '',
								onHeaders: [Function: parserOnHeaders],
								onHeadersComplete: [Function: parserOnHeadersComplete],
								onBody: [Function: parserOnBody],
								onMessageComplete: [Function: parserOnMessageComplete],
								socket: [Object],
								incoming: [Circular],
								maxHeaderPairs: 2000,
								onIncoming: [Function: parserOnIncomingClient] },
				 res: [Circular] } }
